---
# Port Mapper Configuration File

# Column mapping configuration
# Defines which CSV columns to check for each target type
column_mappings:
  # Standard OS exporters - typically found in exporter_name_os column
  exporter_linux:
    column_name: "Exporter_name_os"
  
  exporter_windows:
    column_name: "Exporter_name_os"
    
  exporter_vmware:
    column_name: "Exporter_name_os"
  
  # Application exporters - typically found in app columns
  exporter_jmx:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_cms:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
  
  exporter_aes:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_aessnmp:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_gateway:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_ams:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_sm:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_avayasbc:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_aaep:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_mpp:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_ipo:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_iq:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_weblm:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_aacc:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_wfodb:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_verint:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_network:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_tcti:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_callback:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_nuancelm:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_breeze:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_acm:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_kafka:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_drac:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_pfsense:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_aic:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_voiceportal:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_aam:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_pc5:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_audiocodes:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"
      
  exporter_redis:
    column_names:
      - "Exporter_name_app"
      - "Exporter_name_app_2"
      - "Exporter_name_app_3"

# Port mapping configurations
port_mappings:
  exporter_cms:
    src:  # Source (monitoring server) to target ports
      - ["TCP", "22"]
      - ["ICMP", "ping"] 
      - ["TCP", "443"]
      - ["SSL", "443"]
    dst:  # Destination (target) back to monitoring server ports
      []
  
  exporter_aes:
    src:
      - ["TCP", "22"]
      - ["ICMP", "ping"]
      - ["TCP", "443"] 
      - ["SSL", "8443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
      - ["UDP", "162"]
  
  exporter_aessnmp:
    src:
      - ["TCP", "22"]
      - ["UDP", "161"]
      - ["TCP", "443"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_gateway:
    src: 
      - ["UDP", "161"]
      - ["TCP", "22"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "162"]
  
  exporter_ams:
    src:
      - ["TCP", "22"]
      - ["UDP", "161"]
      - ["TCP", "8443"]
      - ["ICMP", "ping"]
      - ["SSL", "8443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_sm:
    src:
      - ["TCP", "22"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "162"]
  
  exporter_avayasbc:
    src:
      - ["TCP", "22"]
      - ["TCP", "222"]
      - ["UDP", "161"]
      - ["TCP", "443"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_aaep:
    src:
      - ["TCP", "22"]
      - ["TCP", "5432"]
      - ["UDP", "161"]
      - ["TCP", "443"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_mpp:
    src:
      - ["TCP", "22"]
      - ["ICMP", "ping"]
    dst: []
  
  exporter_windows:
    src:
      - ["TCP", "9182"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_linux:
    src:
      - ["TCP", "22"]
      - ["ICMP", "ping"]
    dst: []
  
  exporter_ipo:
    src:
      - ["TCP", "22"]
      - ["TCP", "443"]
      - ["UDP", "161"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_iq:
    src:
      - ["TCP", "22"]
      - ["TCP", "443"]
      - ["ICMP", "ping"]
    dst: []
  
  exporter_weblm:
    src:
      - ["TCP", "22"]
      - ["TCP", "443"]
      - ["TCP", "52233"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
      - ["SSL", "52233"]
    dst: []
  
  exporter_aacc:
    src:
      - ["TCP", "9182"]
      - ["TCP", "8443"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_wfodb:
    src:
      - ["TCP", "1433"]
      - ["TCP", "9182"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_verint:
    src:
      - ["TCP", "9182"]
      - ["ICMP", "ping"]
      - ["TCP", "8443"]
      - ["SSL", "8443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_network:
    src:
      - ["UDP", "161"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_tcti:
    src:
      - ["TCP", "8080"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_callback:
    src:
      - ["TCP", "1433"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_nuancelm:
    src:
      - ["TCP", "9182"]
      - ["TCP", "27000"]
      - ["ICMP", "ping"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_jmx:
    src:
      - ["TCP", "7080"]
      - ["ICMP", "ping"]
    dst: []
  
  exporter_breeze:
    src:
      - ["TCP", "22"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_acm:
    src:
      - ["TCP", "22"]
      - ["TCP", "5022"]
      - ["TCP", "443"]
      - ["UDP", "161"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
      - ["UDP", "162"]
  
  exporter_vmware:
    src:
      - ["TCP", "22"]
      - ["ICMP", "PING"]
      - ["TCP", "443"]
    dst: []
  
  exporter_kafka:
    src:
      - ["TCP", "9092"]
    dst: []
  
  exporter_drac:
    src:
      - ["TCP", "22"]
      - ["ICMP", "PING"]
      - ["UDP", "161"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_pfsense:
    src:
      - ["TCP", "22"]
      - ["ICMP", "PING"]
      - ["UDP", "161"]
    dst:
      - ["UDP", "162"]
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_aic:
    src:
      - ["TCP", "9183"]
      - ["ICMP", "ping"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
  
  exporter_voiceportal:
    src:
      - ["TCP", "5432"]
      - ["ICMP", "ping"]
      - ["TCP", "443"]
      - ["TCP", "22"]
    dst: []
  
  exporter_aam:
    src:
      - ["ICMP", "ping"]
      - ["TCP", "8443"]
      - ["TCP", "22"]
      - ["UDP", "161"]
      - ["SSL", "8443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
      - ["UDP", "162"]
  
  exporter_pc5:
    src:
      - ["ICMP", "ping"]
      - ["TCP", "22"]
    dst: []
  
  exporter_audiocodes:
    src:
      - ["ICMP", "ping"]
      - ["TCP", "22"]
      - ["UDP", "161"]
      - ["SSL", "443"]
    dst:
      - ["UDP", "514"]
      - ["TCP", "514"]
      - ["UDP", "162"]
      - ["SSL", "443"]
  
  exporter_redis:
    src:
      - ["TCP", "6379"]
    dst: []